spring:
  application:
    name: jwt-security

  datasource:
    url: jdbc:postgresql://localhost:5432/security_user_details
    username: postgres
    password: vignesh
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # or 'create' if you uncomment
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      springframework:
        boot:
          sql:
            init: DEBUG
        jdbc:
          datasource:
            init: DEBUG


