server:
  port: 8081

spring:
  application:
    name: patient-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/healthcare-realm
          jwk-set-uri: http://localhost:8080/realms/healthcare-realm/protocol/openid-connect/certs


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-service:8763/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    com.vignesh.audit: DEBUG
#  file:
#    name: /var/log/microservices/patient-service.log
#  pattern:
#    level: "%5p [traceId=%X{traceId}, spanId=%X{spanId}]"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  tracing:
    sampling:
      probability: 1
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"









#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


#Only should invoke at starting and first time
#spring.sql.init.mode = always

#mysql
#spring.datasource.url=jdbc:mysql://localhost:3306/patient_records
#spring.datasource.username =root
#spring.datasource.password =vig24nesh*
#
#spring.jpa.hibernate.ddl-auto=update
#
#
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true



#spring.jpa.hibernate.ddl-auto=create

#spring.main.banner-mode=console
#spring.jpa.show-sql=true
##spring.jpa.hibernate.ddl-auto=update

# **CRITICAL CHANGE:** Use the database container's SERVICE NAME as the host
# 'patient-db' is the name we will give the database service in docker-compose.yml
#spring.datasource.url=jdbc:postgresql://patient-service-db:5432/db
#spring.datasource.username=admin_user
#spring.datasource.password=vignesh
#spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#
#
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
#logging.level.org.springframework.boot.sql.init=DEBUG
#logging.level.org.springframework.jdbc.datasource.init=DEBUG


#eureka
#eureka.client.service-url.defaultZone = http://eureka-server-service:8763/eureka/
#eureka.client.register-with-eureka = true
#eureka.client.fetch-registry = true
#eureka.instance.prefer-ip-address = true

