spring:
  application:
    name: eureka-server-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8763/eureka/  # âœ… Use new port only
  instance:
    prefer-ip-address: true
server:
  port: 8763
